CREATE TABLE PLAYER(PLAYERID VARCHAR(10) PRIMARY KEY,PLAYERNAME VARCHAR(15),AGE
VARCHAR(10));
DESC PLAYER;
CREATE TABLE TEAM(TEAMID VARCHAR(10) PRIMARY KEY,TEAMNAME VARCHAR(10),CITY
VARCHAR(10),COACH VARCHAR(15) ,CAPTAIN VARCHAR(10) REFERENCES PLAYER(PLAYERID));
DESC TEAM;
CREATE TABLE MATCH1(MATCH1ED VARCHAR(10) PRIMARY KEY,RESULT VARCHAR(10) REFERENCES
TEAM(TEAMID),MOM VARCHAR(10) REFERENCES PLAYER(PLAYERID));
DESC MATCH1;
CREATE TABLE STADIUM(STADIUMID VARCHAR(10) PRIMARY KEY,SNAME VARCHAR(10) ,CITY
VARCHAR(10),AREA VARCHAR(10));
DESC STADIUM;
CREATE TABLE PLAYEDFOR(PLAYERID VARCHAR(10) ,TEAMID VARCHAR(10));
DESC PLAYEDFOR;
INSERT INTO PLAYER VALUES('&PLAYERID','&PLAYERNAME','&AGE');
 select * from PLAYER;
INSERT INTO TEAM VALUES('&TEAMID','&TEAMNAME','&CITY', '&COACH', '&CAPTAIN');
select * from TEAM;
INSERT INTO MATCH1 VALUES('&MATCHED','&RESULT','&MOM');
 select * from MATCH1;
 INSERT INTO STADIUM VALUES('&STADIUMID','&SNAME' ,'&CITY','&AREA');
 select * from STADIUM;
INSERT INTO PLAYEDFOR VALUES('&PLAYERID','& TEAMID ');



