CREATE TABLE BRANCH(BRANCH_ID VARCHAR(10) PRIMARY
KEY,BRANCHNAME VARCHAR(15),HOD VARCHAR(10));
desc BRANCH;
CREATE TABLE STUDENT(USN VARCHAR(10) PRIMARY KEY,NAME
VARCHAR(10),ADDRESS VARCHAR(15),SEM VARCHAR(5) ,BRANCH_ID
VARCHAR(10) REFERENCES BRANCH(BRANCH_ID));
 desc student;
 CREATE TABLE AUTHOR2(AUTHOR2_ID VARCHAR(10) PRIMARY
KEY,AUTHOR2NAME VARCHAR(15),COUNTRY VARCHAR(15));
DESC AUTHOR;
CREATE TABLE BOOK(BOOK_ID VARCHAR(10) PRIMARY KEY,BOOKNAME
VARCHAR(15),AUTHOR_ID VARCHAR(10) REFERENCES
AUTHOR(AUTHOR_ID),PUBLISHER VARCHAR(10),BRANCH_ID VARCHAR(10)
REFERENCES BRANCH(BRANCH_ID) );
DESC BOOK;
CREATE TABLE BORROW(USN VARCHAR(10) REFERENCES
STUDENT(USN),BOOK_ID VARCHAR(10) REFERENCES
BOOK(BOOK_ID),BORROWEDDATE VARCHAR(15));
DESC BORROW;
INSERT INTO BRANCH VALUES('&BRANCH_ID','&BRANCHNAME','&HOD');
select * from branch;

INSERT INTO STUDENT VALUES('&USN ','&NAME','&ADDRESS','&SEM
','&BRANCH_ID');
 select * from student;
INSERT INTO BOOK VALUES('&BOOK_ID
','&BOOKNAME','&AUTHOR2_ID','&PUBLISHER','&BRANCH_ID');



